name: CI
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"
    tags:
      - "release-v*"
jobs:
  #  build-native:
  #    name: Build Natives ${{ matrix.os }}
  #    runs-on: ${{ matrix.os }}
  #    strategy:
  #      matrix:
  #        include:
  #          - target: linux_x86_64
  #            os: ubuntu-latest
  #          - target: mac_x86_64
  #            os: macos-latest

  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-prereqs
        with:
          bti_secret: ${{ secrets.SUB_BTI }}
          cwe_secret: ${{ secrets.SUB_CWE_CHECKER }}

      - name: "Setup Ghidra"
        run: |
          wget https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.2.2_build/ghidra_10.2.2_PUBLIC_20221115.zip --output-document=ghidra.zip
          unzip ghidra.zip
          echo "GHIDRA_INSTALL_DIR=$(pwd)/ghidra_10.2.2_PUBLIC" >> $GITHUB_ENV

      - name: "Lint, Build, and Test BTI"
        run: |
          just test
